name: Airdrop
version: 1.0
main: com.ned.airdrop.airdrop
author: ned
api-version: 1.13
description: A plugin that allows players to create Netherite axes at specified coordinates.
commands:
  airdrop:
    description: Creates a Netherite axe at specified coordinates.
    usage: /airdrop <x> <y> <z>